#!/bin/sh

dyndnssh_root="$(pwd)"
tmp_dir="$(mktemp -d)"

cd "$tmp_dir"

egrep "^\." "$TINYDNS_ROOT/data" > data

for hostname in $(ls "$dyndnssh_root/db/ip4"); do
  address="$(head -1 "$dyndnssh_root/db/ip4/$hostname")"
  "$TINYDNS_ROOT/add-host" "$hostname.$TINYDNS_DOMAIN" $address
done

for hostname in $(ls "$dyndnssh_root/db/ip6"); do
  address="$(head -1 "$dyndnssh_root/db/ip6/$hostname")"
  "$TINYDNS_ROOT/add-host6" "$hostname.$TINYDNS_DOMAIN" $address
done

cat data \
  | sed -E "s/(^=.*):[[:digit:]]+$/\1:600/" \
  | sed -E "s/(^6.*):[[:digit:]]+$/\1:600/" \
  > data.new && mv data.new "$TINYDNS_ROOT/data"

rm -rf "$tmp_dir"

cd "$TINYDNS_ROOT" && make > /dev/null 2>&1
